<style>
    .media-options {
        margin-bottom: 20px;
    }
    .media-options::after {
        clear: both;
        content: "";
        display: block;
    }
    .media-options .btn-group {
        margin-bottom: 0;
    }
    .media-option-group {
        margin: 0 0 0 5px;
    }
    .media-option-group label {
        margin-bottom: 0 !important;
    }
    .media-manager .thmb {
        border: 1px solid #e7e7e7;
        border-radius: 3px;
        margin-bottom: 20px;
        padding: 10px;
        position: relative;
    }
    .media-manager .thmb.checked {
        background-color: #fcfcfc;
        border-color: #bbb;
    }
    .media-manager .thmb::after {
        clear: both;
        content: "";
        display: block;
    }
    .media-manager .ckbox {
        display: block;
        left: 15px;
        position: absolute;
        top: 15px;
    }
    .media-manager .fm-group {
        display: block;
        position: absolute;
        right: 15px;
        top: 15px;
    }
    .media-manager .fm-toggle {
        background: none repeat scroll 0 0 #fff;
        border-radius: 2px;
        line-height: normal;
        padding: 1px 4px;
    }
    .media-manager .fm-menu {
        min-width: 120px;
    }
    .media-manager .fm-menu a {
        color: #333;
        font-size: 12px;
        padding: 4px 8px;
    }
    .media-manager .fm-menu i {
        color: #999;
        font-size: 13px;
        margin-right: 7px;
        width: 16px;
    }
    .media-manager .thmb-prev {
        background: none repeat scroll 0 0 #eee;
        overflow: hidden;
    }
    .media-manager .thmb-prev a {
        display: block;
    }
    .media-manager .fm-title {
        font-size: 13px;
        margin-bottom: 0;
    }
    .media-manager .fm-title a {
        display: block;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    .media-manager-sidebar {
        padding-left: 10px;
    }
    .media-manager-sidebar .lg-title a {
        color: #999;
        font-size: 11px;
    }
    .media-manager-sidebar .lg-title a:hover {
        color: #333;
        text-decoration: none;
    }
</style>
<div class="row media-manager">

    <div class="col-xs-6 col-sm-4 col-md-3 document">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check1">
                <label for="check1"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">MyDocuments.doc</a></h5>
            <small class="text-muted">Added: Jan 03, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 image">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check2">
                <label for="check2"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <a data-rel="prettyPhoto" href="images/photos/media1.jpg">
                    <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
                </a>
            </div>
            <h5 class="fm-title"><a href="">Vegetarian.png</a></h5>
            <small class="text-muted">Added: Jan 02, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 video">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check3">
                <label for="check3"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">DogAnimation.mp4</a></h5>
            <small class="text-muted">Added: Jan 02, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 audio">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check7">
                <label for="check7"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">WreckingBall.mp3</a></h5>
            <small class="text-muted">Added: Jan 01, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 image">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check4">
                <label for="check4"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <a data-rel="prettyPhoto" href="images/photos/media3.png">
                    <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
                </a>
            </div>
            <h5 class="fm-title"><a href="">MyFirstArt.png</a></h5>
            <small class="text-muted">Added: Jan 01, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 document">
        <div class="thmb">
            <div class="ckbox ckbox-default">
                <input type="checkbox" value="1" id="check5">
                <label for="check5"></label>
            </div>
            <div class="btn-group fm-group">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">MyResume.docx</a></h5>
            <small class="text-muted">Added: Jan 01, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 video">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check6">
                <label for="check6"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">MyFirstMovie.mp4</a></h5>
            <small class="text-muted">Added: Jan 01, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 image">
        <div class="thmb">
            <div class="ckbox ckbox-default">
                <input type="checkbox" value="1" id="check13">
                <label for="check13"></label>
            </div>
            <div class="btn-group fm-group">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <a data-rel="prettyPhoto" href="images/photos/media2.png">
                    <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
                </a>
            </div>
            <h5 class="fm-title"><a href="">MeAndFriends.png</a></h5>
            <small class="text-muted">Added: Jan 01, 2014</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 audio">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check8">
                <label for="check8"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">IWillSurvive.mp3</a></h5>
            <small class="text-muted">Added: Dec 31, 2013</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 document">
        <div class="thmb">
            <div class="ckbox ckbox-default" style="display: block;">
                <input type="checkbox" value="1" id="check9">
                <label for="check9"></label>
            </div>
            <div class="btn-group fm-group" style="display: block;">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">MyDocuments.doc</a></h5>
            <small class="text-muted">Added: Dec 31, 2013</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 image">
        <div class="thmb">
            <div class="ckbox ckbox-default">
                <input type="checkbox" value="1" id="check10">
                <label for="check10"></label>
            </div>
            <div class="btn-group fm-group">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <a data-rel="prettyPhoto" href="images/photos/media6.png">
                    <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
                </a>
            </div>
            <h5 class="fm-title"><a href="">GreatCity.png</a></h5>
            <small class="text-muted">Added: Dec 30, 2013</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

    <div class="col-xs-6 col-sm-4 col-md-3 video">
        <div class="thmb">
            <div class="ckbox ckbox-default">
                <input type="checkbox" value="1" id="check11">
                <label for="check11"></label>
            </div>
            <div class="btn-group fm-group">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                    <span class="caret"></span>
                </button>
                <ul role="menu" class="dropdown-menu fm-menu pull-right">
                    <li><a href="#"><i class="fa fa-share"></i> Share</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> Email</a></li>
                    <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
                    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                </ul>
            </div><!-- btn-group -->
            <div class="thmb-prev">
                <img alt="" class="img-responsive" src="/users/1/profile/profile_1425555945.jpg" width="150px">
            </div>
            <h5 class="fm-title"><a href="">InTheSea.mp4</a></h5>
            <small class="text-muted">Added: Dec 30, 2013</small>
        </div><!-- thmb -->
    </div><!-- col-xs-6 -->

</div>
<?php
//prx($this->profilePicList);
