<style>
    .media-options {
        margin-bottom: 20px;
    }
    .media-options::after {
        clear: both;
        content: "";
        display: block;
    }
    .media-options .btn-group {
        margin-bottom: 0;
    }
    .media-option-group {
        margin: 0 0 0 5px;
    }
    .media-option-group label {
        margin-bottom: 0 !important;
    }
    .media-manager .thmb {
        border: 1px solid #e7e7e7;
        border-radius: 3px;
        margin-bottom: 20px;
        padding: 10px;
        position: relative;
    }
    .media-manager .thmb.checked {
        background-color: #fcfcfc;
        border-color: #bbb;
    }
    .media-manager .thmb::after {
        clear: both;
        content: "";
        display: block;
    }
    .media-manager .ckbox {
        display: block;
        left: 15px;
        position: absolute;
        top: 15px;
    }
    .media-manager .fm-group {
        display: block;
        position: absolute;
        right: 15px;
        top: 15px;
    }
    .media-manager .fm-toggle {
        background: none repeat scroll 0 0 #fff;
        border-radius: 2px;
        line-height: normal;
        padding: 1px 4px;
    }
    .media-manager .fm-menu {
        min-width: 120px;
    }
    .media-manager .fm-menu a {
        color: #333;
        font-size: 12px;
        padding: 4px 8px;
    }
    .media-manager .fm-menu i {
        color: #999;
        font-size: 13px;
        margin-right: 7px;
        width: 16px;
    }
    .media-manager .thmb-prev {
        background: none repeat scroll 0 0 #eee;
        overflow: hidden;
    }
    .media-manager .thmb-prev a {
        display: block;
    }
    .media-manager .fm-title {
        font-size: 13px;
        margin-bottom: 0;
    }
    .media-manager .fm-title a {
        display: block;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    .media-manager-sidebar {
        padding-left: 10px;
    }
    .media-manager-sidebar .lg-title a {
        color: #999;
        font-size: 11px;
    }
    .media-manager-sidebar .lg-title a:hover {
        color: #333;
        text-decoration: none;
    }
</style>
<div class="row media-manager">  
    <?php if (count($this->profilePicList) > 0) { ?>
        <?php
        foreach ($this->profilePicList as $index => $picture) {

            $imagePath = substr($picture, 6);
            $fileName = basename($imagePath);
            $timestamp = substr($fileName, 8, 10);
            $ext       = $ext = pathinfo($picture, PATHINFO_EXTENSION);
            
            ?>
            <div class="col-xs-6 col-sm-4 col-md-3 document">
                <div class="thmb">
                    <!--
                    <div class="ckbox ckbox-default" style="display: block;">
                        <input type="checkbox" value="1" id="check1">
                        <label for="check1"></label>
                    </div>
                    //-->
                    <div class="btn-group fm-group" style="display: block;">
                        <button data-toggle="dropdown" class="btn btn-default dropdown-toggle fm-toggle" type="button">
                            <span class="caret"></span>
                        </button>
                        <ul role="menu" class="dropdown-menu fm-menu pull-right">
                            <li><a href="<?php echo $this->basePath(); ?>/user/account/download-user-pic/token/<?php echo $timestamp; ?>/ext/<?php echo $ext; ?>" ><i class="fa fa-download"></i> Download</a></li>
                            <li><a href="#" onclick="deletePic('<?php echo $timestamp; ?>', '<?php echo $ext; ?>')"><i class="fa fa-trash-o"></i> Delete</a></li>
                        </ul>
                    </div><!-- btn-group -->
                    <div class="thmb-prev">
                        <img alt="" class="img-responsive" src="<?php echo $this->basePath() . $imagePath; ?>" width="150px">
                    </div>
                    <h5 class="fm-title"><a href=""><?php echo $fileName; ?></a></h5>
                    <small class="text-muted">Added: <?php echo gmdate("d-M-Y",
                $timestamp);
            ?></small>
                </div><!-- thmb -->
            </div><!-- col-xs-6 -->
        <?php } ?>    
<?php } ?>
</div>