<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Custom Tabs -->
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a id="manageProfile" href="#tab_1" data-toggle="tab">Manage Profile</a></li>
                    <li><a id="manageAddress" href="#tab_2" data-toggle="tab">Manage Address</a></li>
                    <li><a id="manageSocialInfo" href="#tab_3" data-toggle="tab">Manage Social Details</a></li>
                    <li><a id="uploadPicture" href="#tab_4" data-toggle="tab">Upload Profile Picture</a></li>
                    <li><a id="manageStore" href="#tab_5" data-toggle="tab">Manage Stores</a></li>
                    <li><a id="manageOffer" href="#tab_6" data-toggle="tab">Manage Offers</a></li>
                    <li><a id="manageSetting" href="#tab_7" data-toggle="tab">Settings</a></li>                    
                    <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab_1">
                        
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_2">
                        
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_3">
                        
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_4">
                        
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_5">
                        
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_6">
                        
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_7">
                        
                    </div><!-- /.tab-pane -->
                </div><!-- /.tab-content -->
            </div><!-- nav-tabs-custom -->
        </div><!-- /.col -->
    </div>
</section>
