<?php
if (count($this->userDetails) > 0) {

    echo $this->headScript()
            ->prependFile($this->basePath() . '/js/module/user/account/profile.js');
    ?>
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div class="box box-primary">
                    <?php
                    $form = $this->profileForm;

                    $form->setAttribute('action',
                            '/user/account/process-profile-update')->prepare();
                    echo $this->form()->openTag($form);
                    $content = $form->get('ProfileFieldset');
                    ?>
                    <div class="box-body">
                        <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('firstName')); ?></label>
                            <?php echo $this->formElement($content->get('firstName')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa fa-times-circle-o"></i>
                                <?php echo $this->formElementErrors($content->get('firstName')); ?>
                            </label>
                        </div>
                        <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('lastName')); ?></label>
                            <?php echo $this->formElement($content->get('lastName')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa fa-times-circle-o"></i>
                                <?php echo $this->formElementErrors($content->get('lastName')); ?>
                            </label>
                        </div>
                        <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('gender')); ?></label>
                            <?php echo $this->formElement($content->get('gender')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa fa-times-circle-o"></i>
                                <?php echo $this->formElementErrors($content->get('gender')); ?>
                            </label>
                        </div>
                        <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('dob')); ?></label>
                            <?php echo $this->formElement($content->get('dob')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa fa-times-circle-o"></i>
                                <?php echo $this->formElementErrors($content->get('dob')); ?>
                            </label>
                        </div>
                        <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('mobileNumber')); ?></label>
                            <?php echo $this->formElement($content->get('mobileNumber')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa fa-times-circle-o"></i>
                                <?php echo $this->formElementErrors($content->get('mobileNumber')); ?>
                            </label>
                        </div>
                    </div>
                    <div class="box-footer">
                        <?php
                        echo $this->formHidden($form->get('csrf'));
                        echo $this->formHidden($content->get('userId'));
                        echo $this->formElement($form->get('submit'));
                        ?>  
                    </div>
                    <?php echo $this->form()->openTag($form); ?>
                </div>
            </div>
        </div>
    </section>

    <?php
} else {
    ?>
    <div class="alert alert-warning alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
        <h4><i class="icon fa fa-warning"></i> Alert!</h4>
        There was some error. Try again.
    </div>
    <?php
}