<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/module/user/account/address.js');
?>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <?php
                $form = $this->addressForm;

                $form->setAttribute('action',
                        '/user/account/process-address-update')->prepare();
                echo $this->form()->openTag($form);
                $content = $form->get('AddressFieldset');
                ?>
                <div class="box-body">
                    <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('countryId')); ?></label>
                            <?php echo $this->formElement($content->get('countryId')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa  "></i>
                                <?php echo $this->formElementErrors($content->get('countryId')); ?>
                            </label>
                        </div>
                    <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('stateId')); ?></label>
                            <?php echo $this->formElement($content->get('stateId')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa  "></i>
                                <?php echo $this->formElementErrors($content->get('stateId')); ?>
                            </label>
                        </div>
                    <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('cityId')); ?></label>
                            <?php echo $this->formElement($content->get('cityId')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa  "></i>
                                <?php echo $this->formElementErrors($content->get('cityId')); ?>
                            </label>
                        </div>
                    <div class="form-group">
                            <label><?php echo $this->formlabel($content->get('address')); ?></label>
                            <?php echo $this->formElement($content->get('address')); ?>
                            <label for="inputError" class="control-label">
                                <i class="fa  "></i>
                                <?php echo $this->formElementErrors($content->get('address')); ?>
                            </label>
                        </div>
                </div>
                <div class="box-footer">
                        <?php
                        echo $this->formHidden($form->get('csrf'));
                        echo $this->formHidden($content->get('userId'));
                        echo $this->formElement($form->get('submit'));
                        ?>  
                    </div>
                <?php
                echo $this->form()->openTag($form);
                ?>
            </div>
        </div>
    </div>
</section>