<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/module/store/offer/offer.js');
?>

<section class="content">
    <div class="row">
        <div class="col-md-4">
            <div class="box box-primary" id="manageOfferBox">
                <div class="box-header">
                    <h3 class="panel-title"><?php echo $this->translate('Add Offer') ?></h3>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="panel-title"><?php echo $this->translate('Offer List') ?></h3>
                    <input type="hidden" name="pageNo" id="pageNo" value="1" />
                    <input type="hidden" name="columnName" id="columnName" value="title" />
                    <input type="hidden" name="sortBy" id="sortBy" value="asc" />
                </div><!-- /.box-header -->
                <div class="box-body" id="offerListResponse">

                </div><!-- /.box-body -->

            </div>
        </div>
        <div class="col-md-8" id="offerDetailBox" style="display: none;">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="panel-title"><?php echo $this->translate('Offer Details') ?></h3>
                </div>
                <div class="box-body" id="viewOfferResponse">

                </div>
                <div class="box-footer">
                    <input type="button" name="close" value="Close" class="btn btn-warning btn-flat" onclick="closeOfferDetailBox()"/>
                </div>
            </div>
        </div>
    </div>
</section>
