<?php

$form = $this->resetPasswordForm;

$form->setAttribute('action', '/user/forgot-password/process-reset-password')->prepare();
echo $this->form()->openTag($form);
$content = $form->get('ResetPasswordFieldset');
?>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Reset Password Form') ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-row">
                    <div class="field-type1 float-l">
                        <label class="form-label-half"><?php echo $this->formlabel($content->get('currentPassword')); ?></label>
                        <div class="form-fields full-width-half">
                            <?php echo $this->formElement($content->get('currentPassword')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('currentPassword')); ?></span>
                        </div>
                    </div>
                </div>
                <br />
                <div class="form-row">
                    <div class="field-type1 float-l">
                        <label class="form-label-half"><?php echo $this->formlabel($content->get('password')); ?></label>
                        <div class="form-fields full-width-half">
                            <?php echo $this->formElement($content->get('password')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('password')); ?></span>
                        </div>
                    </div>
                </div>
                <br />
                <div class="form-row">
                    <div class="field-type1 float-l">
                        <label class="form-label-half"><?php echo $this->formlabel($content->get('confirmPassword')); ?></label>
                        <div class="form-fields full-width-half">
                            <?php echo $this->formElement($content->get('confirmPassword')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('confirmPassword')); ?></span>
                        </div>
                    </div>
                </div>
                <br />
                <div class="form-row">
                    <div class="sign-btn">
                        <?php
                        echo $this->formHidden($form->get('csrf'));
                        echo $this->formElement($content->get('resetPasswordToken'));
                        echo $this->formElement($form->get('resetpassword'));
                        
                        ?>
                        <a href="<?php echo $this->url('user', array('controller' => 'login', 'action' => 'index')); ?>">Login!</a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>