<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/module/store/store/store.js');
?>

<section class="content">
    <div class="row">
        <div class="col-md-4">
            <div class="box box-primary" id="manageStoreBox">
                <div class="box-header">
                    <h3 class="panel-title"><?php echo $this->translate('Add Store') ?></h3>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="panel-title"><?php echo $this->translate('Store List') ?></h3>
                    <input type="hidden" name="pageNo" id="pageNo" value="1" />
                    <input	type="hidden" name="columnName" id="columnName" value="store_name" />
                    <input type="hidden" name="sortBy" id="sortBy" value="asc" />
                </div><!-- /.box-header -->
                <div class="box-body" id="storeListResponse">

                </div><!-- /.box-body -->

            </div>
        </div>
        <div id="storeDetailBox" class="nav-tabs-custom col-md-8" style="display: none;padding:0;">
            <!-- Tabs within a box -->
            <ul class="nav nav-tabs pull-right">                
                <li class=""><a data-toggle="tab" href="#store-timings" aria-expanded="true">Timings</a></li>
                <li class=""><a data-toggle="tab" href="#store-pictures" aria-expanded="true">Pictures</a></li>
                <li class="active"><a data-toggle="tab" href="#store-information" aria-expanded="false">Information</a></li>
                <li class="pull-left header"><i class="fa fa-inbox"></i> Store Details</li>
            </ul>
            <div class="tab-content no-padding">
                <!-- Morris chart - Sales -->
                <div style="position: relative;" id="store-timings" class="chart tab-pane">
                    Manage Store Timings
                </div>
                <div style="position: relative;" id="store-pictures" class="chart tab-pane">
                    Upload Store Picture
                </div>
                <div style="position: relative;" id="store-information" class="chart tab-pane active">
                    Store Information
                </div>
            </div>
        </div>
    </div>
</section>
