<?php

$form = $this->registerForm;

$form->setAttribute('action', '/user/register/process-registration')->prepare();
echo $this->form()->openTag($form);
$content = $form->get('RegisterFieldset');
?>
<div class="login-box-body">
    <p class="login-box-msg">Registration</p>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('firstName')); ?>                            
            <span class="glyphicon glyphicon-inbox form-control-feedback"></span>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('firstName')); ?></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('lastName')); ?>                            
            <span class="glyphicon glyphicon-inbox form-control-feedback"></span>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('lastName')); ?></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('email')); ?>                            
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('email')); ?></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('password')); ?>                            
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('password')); ?></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('confirmPassword')); ?>                            
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('confirmPassword')); ?></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('gender')); ?>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('gender')); ?></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formElement($content->get('userRoleId')); ?>
            <span class="common-error-msg"><?php echo $this->formElementErrors($content->get('userRoleId')); ?></span>
        </div>
        <div class="row">
            <div class="col-xs-8">    
               &nbsp;                      
            </div><!-- /.col -->
            <div class="col-xs-4">
                <?php
                        echo $this->formHidden($form->get('csrf'));
                        echo $this->formHidden($content->get('createdOn'));
                        echo $this->formElement($form->get('register'));                    
                        ?>
            </div><!-- /.col -->
        </div>
    <?php echo $this->form()->closeTag($form); ?>

    <a href="<?php echo $this->url('user/default', array('controller' => 'login')) ?>">Login</a>

</div><!-- /.login-box-body -->